print('Adını yazarmısın')
name=input()
print('Tamam adını kaydettim ^w^   ' + name)
print('Benim adım tilki tanıştığımıza memnun oldum   ' + name)
kişilik=input()
print('Hangi oyunları seversin   ' + name)
kişilik=input()
print('OwO güzel   ' + name)
print('Ben oyun oynamam çünki ben..')
print('GLOBALİM XD')
print('Vayy senle arkadaş olduk deilmi   ' + name)
kişilik=input()
print('HeHeHe')
print('Ben burda depresyonda olmaman ve sohbet edeceğin bir tilki olarak yapıldım :D   ' + name)
